name: Conda Build

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set pytorch-3dunet version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Print pytorch-3dunet version
      run: |
        echo $RELEASE_VERSION
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Build pytorch-3dunet
      run: |
          conda install -q conda-build
          conda build -c pytorch -c nvidia -c conda-forge conda-recipe
    - name: Install dependencies
      run: |
        conda install -c pytorch -c nvidia -c conda-forge --use-local pytorch-3dunet
    - name: Run pytest
      run: |
        # workaround ImportError: /usr/share/miniconda/lib/python3.9/site-packages/h5py/defs.cpython-39-x86_64-linux-gnu.so: undefined symbol: H5Pset_fapl_ros3
        conda install -c conda-forge pytest h5py=3.1.0
        pytest
    - name: Deploy on conda
      if: ${{ startsWith( github.ref, 'refs/tags/') && success() }}
      env:
        ANACONDA_SECRET: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        conda install -q anaconda-client
        anaconda -t $ANACONDA_SECRET upload $CONDA/conda-bld/**/pytorch-3dunet-*.tar.bz2
